// <auto-generated />
namespace Menu_Restaurant_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixOrderCustomerRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixOrderCustomerRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "202505130852458_FixOrderCustomerRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
